import fs from 'fs-extra';
import path from 'path';
import { ensureKeysForSchema } from '../utils/ensure-keys.js';
import { defaultFormTemplate } from '../form0-forms/form-schema-template.js';

async function createFormProject(dir, showInstructions = true) {
  const base = path.resolve(process.cwd(), dir);
  await fs.ensureDir(base);

  // Get the default form template and ensure it has keys
  const schema = structuredClone(defaultFormTemplate);
  ensureKeysForSchema(schema.form.elements);

  const testScript = `import { createFormEngine } from 'form0-core';
import fs from 'fs';

const schema = JSON.parse(fs.readFileSync('./form.schema.json', 'utf8'));

console.log('🧪 Testing form0 engine with generated schema...');
console.log('📋 Schema:', schema.form.name);
console.log('📝 Description:', schema.form.description);
console.log();

// Test with sample data
const initialValues = { first_name: 'Alice', age: 21 };
console.log('🔧 Initial values:', JSON.stringify(initialValues, null, 2));
console.log();

const engine = createFormEngine({ schema, initialValues });
engine.eval();

console.log('🧠 Engine state after evaluation:');
const state = engine.getState();
console.log(JSON.stringify(state, null, 2));
console.log();

// Check validation results
const hasErrors = Object.keys(state.errors).length > 0;
console.log('✅ Form validation result:', hasErrors ? 'INVALID' : 'VALID');

if (hasErrors) {
  console.log('❌ Validation errors:');
  for (const [field, error] of Object.entries(state.errors)) {
    console.log('   ' + field + ': ' + error);
  }
} else {
  console.log('🎉 All fields passed validation!');
}
`;

  // Create package.json for ES modules
  const packageJson = {
    name: dir.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
    version: '1.0.0',
    type: 'module',
    description: 'Generated by form0 CLI',
    main: 'test.js',
    scripts: {
      test: 'node test.js'
    },
    dependencies: {
      'form0-core': 'file:../form0-core'
    }
  };

  await fs.writeJson(`${base}/package.json`, packageJson, { spaces: 2 });
  await fs.writeJson(`${base}/form.schema.json`, schema, { spaces: 2 });
  await fs.writeFile(`${base}/test.js`, testScript);
  const readmeContent = `# ${dir}

Generated by \`form0 init\`.

## Files

- \`package.json\` - Node.js project configuration
- \`form.schema.json\` - Your form schema definition
- \`test.js\` - Test script to validate your form
- \`README.md\` - This file

## Setup

First, install dependencies:
\`\`\`bash
npm install
\`\`\`

## Usage

### Test your form
\`\`\`bash
form0 test
# or
node test.js
\`\`\`

### Run with custom values
\`\`\`bash
form0 run form.schema.json --values '{"first_name": "John", "age": 25}'
\`\`\`

### Validate schema
\`\`\`bash
form0 validate form.schema.json
\`\`\`

### Preview form structure
\`\`\`bash
form0 preview form.schema.json
\`\`\`

### Watch for changes
\`\`\`bash
form0 watch form.schema.json --auto-run
\`\`\`
`;

  await fs.writeFile(`${base}/README.md`, readmeContent);

  const displayDir = dir === '.' ? path.basename(process.cwd()) : dir;
  console.log(`✅ Initialized form0 project in ${displayDir}`);
  
  if (showInstructions) {
    console.log();
    console.log('Next steps:');
    if (dir !== '.') {
      console.log(`  cd ${dir}`);
    }
    console.log('  npm install    # Install dependencies');
    console.log('  form0 test     # Run the test (will auto-install if needed)');
    console.log();
    console.log('💡 The project uses a local file reference to form0-core.');
    console.log('   Make sure form0-core is available in the parent directory.');
    console.log();
    console.log('🔧 If npm is not in your PATH, you can also run:');
    console.log('   node test.js   # After manually installing dependencies');
  }
}

// Export the main command for CLI usage
export async function initCommand(dir) {
  return await createFormProject(dir, true);
}

// Export a version for interactive usage without instructions
export async function initForInteractive(dir) {
  return await createFormProject(dir, false);
}
