import fs from 'fs-extra';
import path from 'path';

export async function initCommand(dir) {
  const base = path.resolve(process.cwd(), dir);
  await fs.ensureDir(base);

  const schema = {
    form: {
      name: 'My Form',
      description: 'Generated by form0 CLI',
      elements: [
        {
          type: 'TextField',
          key: 'fld_' + Math.random().toString(36).substring(2, 8),
          data_name: 'first_name',
          label: 'First Name',
          required: true
        }
      ]
    }
  };

  const testScript = `import { createFormEngine } from 'form0';
import schema from './form.schema.json' assert { type: 'json' };

const engine = createFormEngine({ schema, initialValues: { first_name: 'Alice' } });
engine.eval();
console.log(engine.getState());
`;

  await fs.writeJson(`${base}/form.schema.json`, schema, { spaces: 2 });
  await fs.writeFile(`${base}/test.js`, testScript);
  await fs.writeFile(`${base}/README.md`, `# ${dir}\n\nGenerated by \`form0 init\`.`);

  console.log(`✅ Initialized form0 project in ${dir}`);
}