import fs from 'fs-extra';
import path from 'path';
import { ensureKeysForSchema } from '../utils/ensure-keys.js';
import { defaultFormTemplate } from '../form0-forms/form-schema-template.js';
import { testScriptTemplate } from '../utils/test-template.js';
import { createReadmeTemplate } from '../utils/test-readme.js';
import { t } from '../utils/i18n.js';

async function createFormProject(dir, showInstructions = true) {
  const base = path.resolve(process.cwd(), dir);
  await fs.ensureDir(base);

  // Get the default form template and ensure it has keys
  const schema = structuredClone(defaultFormTemplate);
  ensureKeysForSchema(schema.form.elements);

  const testScript = testScriptTemplate;

  // Create package.json for ES modules
  const packageJson = {
    name: dir.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
    version: '1.0.0',
    type: 'module',
    description: 'Generated by form0 CLI',
    main: 'test.js',
    scripts: {
      test: 'node test.js'
    },
    dependencies: {
      'form0-core': 'file:../form0-core' // TODO: change to form0-core when published
    }
  };

  // Write all files
  await fs.writeJson(`${base}/package.json`, packageJson, { spaces: 2 });
  await fs.writeJson(`${base}/form.schema.json`, schema, { spaces: 2 });
  await fs.writeFile(`${base}/test.js`, testScript);
  await fs.writeFile(`${base}/README.md`, createReadmeTemplate(dir));

  // Show completion message
  const displayDir = dir === '.' ? path.basename(process.cwd()) : dir;
  console.log(t('commands.init.success', { dir: displayDir }));
  
  if (showInstructions) {
    console.log();
    console.log(t('commands.init.nextSteps'));
    if (dir !== '.') {
      console.log(`  cd ${dir}`);
    }
    console.log(`  ${t('commands.init.installDeps')}`);
    console.log(`  ${t('commands.init.runTest')}`);
    console.log();
    console.log(t('commands.init.localFileNote'));
    console.log(t('commands.init.makeAvailable'));
    console.log();
    console.log(t('commands.init.npmNotInPath'));
    console.log(`  ${t('commands.init.manualRun')}`);
  }
}

// Export the main command for CLI usage
export async function initCommand(dir) {
  return await createFormProject(dir, true);
}

// Export a version for interactive usage without instructions
export async function initForInteractive(dir) {
  return await createFormProject(dir, false);
}
