export function createReadmeTemplate(projectName) {
  return `# ${projectName}

Generated by \`form0 init\`.

## Files

- \`package.json\` - Node.js project configuration
- \`form.schema.json\` - Your form schema definition
- \`test.js\` - Test script to validate your form
- \`README.md\` - This file

## Setup

First, install dependencies:
\`\`\`bash
npm install
\`\`\`

## Usage

### Test your form
\`\`\`bash
form0 test
# or
node test.js
\`\`\`

### Run with custom values
\`\`\`bash
form0 run form.schema.json --values '{"first_name": "John", "age": 25}'
\`\`\`

### Validate schema
\`\`\`bash
form0 validate form.schema.json
\`\`\`

### Preview form structure
\`\`\`bash
form0 preview form.schema.json
\`\`\`

### Watch for changes
\`\`\`bash
form0 watch form.schema.json --auto-run
\`\`\`
`;
}
